### ISSUE TITLE
[REQUEST] Add icons from the BC database

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farmingbar#34]
**Is your feature request related to a problem? Please describe.**
Icons for BC items aren't included in the Shopping List or Items icon database.

**Describe the solution you'd like**
If I want an icon from a BC item for a Shopping List or Items, I'd like it available to select.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
No other context needed.

**Comment by rbpaiett** [comment]
The Nethercleft Leg Irons (inv_misc_armorkit_25)
Primal Might (spell_nature_lightningoverload)
Cobrahide Leg Armor (inv_misc_armorkit_21)
Clefthide Leg Armor (inv_misc_armorkit_23)
Grilled Mudfish (inv_misc_food_78)
Cooking Pot (inv_misc_cauldron_arcane)
Spicy Hot Talbuk (inv_misc_food_84_roastclefthoof)

If I find any more, do I post them here or on Curse comments?

**Comment by niketa-wow** [comment]
I get the icon info from a database in LargerMacroItems with permission from one of the authors. I hadn't updated it since BCC, but I did look at theirs and it turns out even that add-on isn't able to get all of the icons.

So, I will try my best to add any that are missing, but will probably need to be told as they're found, since I play retail.

I would appreciate if this is done through GitHub issues, as it's easier for me to track things I need to do. Once I add the ones you've already told me, I will close this issue. However, feel free to reopen it any time you have some to add, or create a new issue. 

Thanks!

**Comment by rbpaiett** [comment]
All right, will send further icon requests this way. Thanks again!

**Comment by niketa-wow** [comment]
Sorry this has taken so long to take care of. Finally finished for the semester, so I had a chance to update this.

https://github.com/niketa-wow/farmingbar/releases/tag/v2.1.7

**Comment by rbpaiett** [comment]
Awesome! You rule.
