### ISSUE TITLE
[BUG] Profile

### ISSUE THREAD

**Issue by Addonman** [niketa-wow/farmingbar#35]
It simply doesnt do  anything. I set it up on one char and has no effect when i try to copy it on another.

**Comment by niketa-wow** [comment]
Is there a lua error? Or does it work after refreshing?

Also to note, the profiles on the stable version don't really work as you may expect them to. This happened been reworked in the alpha.

**Comment by niketa-wow** [comment]
Please see the following issue for the behavior of profiles in the stable version:

https://github.com/niketa-wow/farmingbar/issues/21

**Comment by Addonman** [comment]
There isnt error. What i wanted to save is bar starting position with 0 buttons opened. If  i try to farm i usually farm what i had in mind and just close all opend buttons after i have done farming . Recently there was update and bar was out of position on top of a screen (mine is close t o bottom ) with 6 or so empty buttons to the right. All i wanted is to save time and set position on 1 char , oriented buttons to open to top and then just replicate taht on alts. I just did copy profile from main and that copy did nothing to affect bar. Tried it in couple of alts and didnt work for me.

**Comment by niketa-wow** [comment]
Currently, profiles only set stylistic settings on stable. On the original profile design, this was a hindsight and brought to my attention in issue #21. Because I was already working on a massive rewrite, I chose not to change this on stable, as it would have added a lot of additional time for me.

In the current alpha build, profiles are working as you'd expect them to, but it's still in development, because I've had to put a pause on coding while I was in school this past year. However, I'm taking a break next semester, so I will have some time to continue working on it, and it is already about 3/4 of the way done with alpha.

I am curious why your settings were reset though. Were there changes to any other things, like your preferences?

**Comment by niketa-wow** [comment]
Oh, I'm sorry, I thought you were talking about the stable. Which alpha version is not working? The last one I had submitted was v14 in August. Is that the one? I know I had an issue with it not doing anything in a reload that I took care of in my working copy, but I'm not sure that's the problem you're having.

**Comment by Addonman** [comment]
v2.1.7

**Comment by Addonman** [comment]
Soory i see now that was my mistake last version was stable one

**Comment by niketa-wow** [comment]
Did you upgrade from the previous stable released or did it skip a version?

**Comment by Addonman** [comment]
I have wowup set up to alpha versions. So if previous version vas alpha,beta or stable it was upgraded from that previous version.

**Comment by Addonman** [comment]
And every time before i log into game i run wowup so i pretty much get all versions in order.

**Comment by niketa-wow** [comment]
I see. Do you intend to use stable or alpha?

**Comment by Addonman** [comment]
I usually use last version availeable -be it alpha or stable.So i have most up to date version of addon i use. It wasnt big problem just little bit of time consuming since i am alotholic so i had to do it on few chars.
